language: perl

perl:
    - "5.20"

# Start databases for SQL operation testing
services:
    - mysql
    - postgresql

before_install: 
# Ensure test database
    - mysql -e "create database IF NOT EXISTS test;" -uroot

before_script:
    - cpanm Config::General
    - cpanm -n Devel::Cover::Report::Coveralls
    - cpanm -n JSON
    - cpanm -n REST::Client
    - cpanm -n MIME::Base64

after_script:
    - cover -test -report coveralls

