language: perl
sudo: required
dist: trusty

perl:
- '5.20'

addons:
  postgresql: "9.4"

services:
- postgresql

before_install:
- sudo mkdir /var/log/dbod
- sudo chown travis /var/log/dbod

before_script:
- cpanm Config::General
- cpanm -n Devel::Cover::Report::Coveralls
- cpanm -n JSON
- cpanm -n REST::Client
- cpanm -n MIME::Base64

after_script:
- cover -test -report coveralls

notifications:
  slack:
    secure: WTQ9EGOQVAbjyM3Hirh42ZyYWRP7hHSTMWXFdeNTmnoWGROYP1U+g7OXTL0BnVwILgUgll/r6yyDhtMXioIXFm7gkbpjKlc1CYEOwXW0aSmyxwZ9XA9G6IwTcivx1bLzrutPgFExW6ZlovmLfi4h37qmRcCb3SUpK3eKUSOi8d0=
