language: perl
sudo: required
dist: trusty

perl:
- '5.20'

addons:
  postgresql: "9.4"

services:
- postgresql

before_install:
- sudo mkdir /var/log/dbod
- sudo chown travis /var/log/dbod
- sudo openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv -in resources/netapp-sdk.tar.gz.enc -out resources/netapp-sdk.tar.gz -d
- sudo tar xvzf resources/netapp-sdk.tar.gz -C /opt/

before_script:
- cpanm Config::General
- cpanm -n Devel::Cover::Report::Coveralls
- cpanm -n JSON
- cpanm -n REST::Client
- cpanm -n MIME::Base64

after_script:
- cover -test -ignore_re NaServer.pm,NaElement.pm -report coveralls

notifications:
  slack:
    secure: WTQ9EGOQVAbjyM3Hirh42ZyYWRP7hHSTMWXFdeNTmnoWGROYP1U+g7OXTL0BnVwILgUgll/r6yyDhtMXioIXFm7gkbpjKlc1CYEOwXW0aSmyxwZ9XA9G6IwTcivx1bLzrutPgFExW6ZlovmLfi4h37qmRcCb3SUpK3eKUSOi8d0=
