language: perl

perl:
    - "5.20"

before_install: 
# Change the current directory before doing anything
    - pushd src/
# Copy configuration template to an unprivileged usable location
#  (as defined in share/configpath.conf)
    - cp share/dbod-core.conf-template /tmp/core.conf

before_script:
    - cpanm Config::General
    - cpanm -n Devel::Cover::Report::Coveralls
    - cpanm -n JSON
    - cpanm -n REST::Client
    - cpanm -n MIME::Base64

after_script:
    - cover -test -report coveralls

    
