language: perl

perl:
    - "5.20"

# Change the current directory before doing anything
before_install: 
    - pushd src/

before_script:
    - cpanm Config::General
    - cpanm -n Devel::Cover::Report::Coveralls
    - cpanm -n JSON
    - cpanm -n REST::Client
    - cpanm -n MIME::Base64

after_script:
    - cover -test -report coveralls

    
