#!/usr/bin/env perl

use strict;
use warnings;

use Carp;

use DBOD::Job;
use Data::Dumper;

# Initiates logger
BEGIN { 
    Log::Log4perl->easy_init() ;
}
my $job = DBOD::Job->new_with_options();

sub body {
    my $params = shift;
    my @time = $job->db->select('select now()');
    print Dumper @time;
    $job->db->do('use test',);
    $job->db->do('create table a (a int, b varchar(32))',);
    my @values =  (1, 'test', 2, 'test2');
    $job->db->do('insert into a values (?, ?)', \@values);
    my @result = $job->db->select('select * from a');
    print Dumper @result;
    $job->db->do('drop table a');
    return 0;
}

$job->run(\&body);

