#!/usr/bin/env perl
# Copyright (C) 2015, CERN
# # This software is distributed under the terms of the GNU General Public
# # Licence version 3 (GPL Version 3), copied verbatim in the file "LICENSE".
# # In applying this license, CERN does not waive the privileges and immunities
# # granted to it by virtue of its status as Intergovernmental Organization
# # or submit itself to any jurisdiction.

use strict;
use warnings;

use DBOD::Job;
use Data::Dumper;

# Initiates logger
BEGIN { 
    Log::Log4perl->easy_init() ;
}
my $job = DBOD::Job->new_with_options();

sub body {
    my $params = shift;
    my @time = $job->db->select('select now()');
    print Dumper @time;
    $job->db->do('use test',);
    $job->db->do('create table a (a int, b varchar(32))',);
    my @values =  (1, 'test', 2, 'test2');
    $job->db->do('insert into a values (?, ?)', \@values);
    my @result = $job->db->select('select * from a');
    print Dumper @result;
    $job->db->do('drop table a');
    return 0;
}

$job->run(\&body);

