#!/usr/bin/env perl
# Copyright (C) 2015, CERN
# This software is distributed under the terms of the GNU General Public
# Licence version 3 (GPL Version 3), copied verbatim in the file "LICENSE".
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as Intergovernmental Organization
# or submit itself to any jurisdiction.

use warnings;
use strict;

use Log::Log4perl;
use DBOD::Job;
use Data::Dumper;
use DBOD::Network::LanDB;
use JSON; 

# Initiates logger
INIT { 
    Log::Log4perl->easy_init() ;
}
my $job = DBOD::Job->new_with_options( allow_empty_metadata => 1);

$ENV{PERL_LWP_SSL_VERIFY_HOSTNAME}=0;

sub body {
    my $params = shift;
    my $result = DBOD::Network::LanDB::get_ip_alias($job->entity(), $job->config);
    print Dumper $result;
    if (defined $result and (scalar @{$result} > 0)) {
        $job->log->debug('Removing ip alias');
        $result = DBOD::Network::LanDB::remove_ip_alias('db-dbod-699', $job->entity, $job->config);
        print Dumper $result;
    }
    else {
        $job->log->debug('Adding ip alias');
        $result = DBOD::Network::LanDB::add_ip_alias('db-dbod-699', $job->entity, $job->config);
        print Dumper $result;
    }
    return 0;
}

$job->run(\&body);

