#!/usr/bin/env perl
# Copyright (C) 2015, CERN
# This software is distributed under the terms of the GNU General Public
# Licence version 3 (GPL Version 3), copied verbatim in the file "LICENSE".
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as Intergovernmental Organization
# or submit itself to any jurisdiction.

# Extension of the base DBOD::Job class to add extra required parameters
package ping;
use Moose;
extends 'DBOD::Job';
#has 'help' => 
#    (is => 'ro', isa => 'Bool', documentation => qq{Print command usage} );

# Main
package main;

use strict;
use warnings;

use Log::Log4perl;
use DBOD qw( $ERROR $OK);
use DBOD::Systems::PG;
use Try::Tiny;
use Data::Dumper;

# Initiates logger
BEGIN { 
    Log::Log4perl->easy_init() ;
}

my $job = ping->new_with_options();

sub body {

    $job->log->info('Pinging '. $job->entity );

	my $pg = DBOD::Systems::PG->new(
		instance => $job->entity(),
		metadata => $job->metadata(),
		config => $job->config(),
	);

    try {
        $pg->_connect_db();
        unless($pg->db->do('delete from dod_ping') == 1) {
            $job->log->debug('Problem deleting entry from ping table');
        };
        unless($pg->db->do('insert into dod_ping select current_date, current_time') == 1) {
            $job->log->debug('Problem deleting entry from ping table');
            $job->log->debug("Database seems UP but not responsive");
        }
        $job->log->debug("Database is UP and responsive");
    } catch {
        $job->log->error("Problem connecting to database. DB object:");
        $job->log->debug( Dumper $pg->db() );
        return $ERROR;

    };

	return $OK;	
}

$job->run(\&body);

