#!/usr/bin/env perl
# Copyright (C) 2015, CERN
# This software is distributed under the terms of the GNU General Public
# Licence version 3 (GPL Version 3), copied verbatim in the file "LICENSE".
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as Intergovernmental Organization
# or submit itself to any jurisdiction.

use strict;
use warnings;

use DBOD::Job;
use Data::Dumper;

# Initiates logger
BEGIN { 
    Log::Log4perl->easy_init() ;
}
my $job = DBOD::Job->new_with_options();
$job->connect_db();

sub body {
    my $params = shift;
    my $type = lc $job->metadata->{'subcategory'};
    $job->db->execute_sql_file($job->config->{$type}->{'helper_ping'});
    $job->_output(0);
}

$job->run(\&body);
