---
author:
  - 'Ignacio Coterillo <ignacio.coterillo@cern.ch>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: gplv3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBOD
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Config::General: 0
  DBD::Oracle: 0
  File::ShareDir: 0
  Log::Log4perl: 0
  Moose: 0
  MooseX::Getopt: 0
  MooseX::Log::Log4perl: 0
  MooseX::Role::DBIx::Connector: 0
  REST::Client: 0
  Switch: 0
  YAML::Syck: 0
version: '0.5'
